version: '2'
services:
  cafes:
    build:
      context: ./data_server
      dockerfile: app.dockerfile
  auth:
    build:
      context: ./auth_server
      dockerfile: app.dockerfile
  api:
    build:
      context: ./api_gateway
      dockerfile: app.dockerfile
    environment:
      - "DATA_API=http://cafes:5000"
    depends_on:
      - cafes
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./client
      dockerfile: app.dockerfile
    ports:
      - "8080:80"
    
